# Generated by Django 5.0.1 on 2024-02-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='from_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='to_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
