# Generated by Django 5.0.1 on 2024-02-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_booking_passenger_age_booking_passenger_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id',
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
