# Generated by Django 5.0.1 on 2024-02-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_remove_flight_id_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
