# Generated by Django 5.0.1 on 2024-06-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_mybookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybookings',
            name='date',
        ),
    ]
